from .usuario import usuario as UsuarioResource
from .usuario import usuarios as UsuariosResource
from .plan import plan as PlanResource
from .plan import planes as PlanesResource
from .notificacion import notificacion as NotificacionResource
from .notificacion import notificaciones as NotificacionesResource
from .ficha import ficha as FichaResource
from .ficha import fichas as FichasResource
from .auth import login as LoginResource
from .auth import logout as LogoutResource
from .auth import Register as RegisterResource
from .ejercicios import ejercicio as EjercicioResource
from .ejercicios import ejercicios as EjerciciosResource
from .rutina import rutina as RutinaResource
from .rutina import rutinas as RutinasResource
from .sesion import sesion as SesionResource
from .sesion import sesiones as SesionesResource
from .ejercicio_rutina import ejercicio_rutina as EjercicioRutinaResource
from .ejercicio_rutina import ejercicios_rutina as EjerciciosRutinaResource
